### ISSUE TITLE
Issues with the theme.

### ISSUE THREAD

**Issue by ghost** [Kurou-kun/ashuramaru-theme#1]
There are several unthemed areas, such as the search area, the emoji picker, the server boost page, among others.

Themes should not outright advise again options such as light mode because you don't want to theme them (my personal opinion, others are fine with it).

Themes should work properly in all message display modes (compact, cozy), currently messages are displayed incorrectly in compact mode making the chat a jumbled mess where links, usernames, user messages, timestamps are all a jumbled mess, practically unusable.

**Comment by Kurou-kun** [comment]
Will re-make entire addons in this week as well rest of the theme

**Comment by Kurou-kun** [comment]
> There are several unthemed areas, such as the search area, the emoji picker, the server boost page, among others.
> 
> Themes should not outright advise again options such as light mode because you don't want to theme them (my personal opinion, others are fine with it).
> 
> Themes should work properly in all message display modes (compact, cozy), currently messages are displayed incorrectly in compact mode making the chat a jumbled mess where links, usernames, user messages, timestamps are all a jumbled mess, practically unusable.

I've made few changes and themed some parts i didn't theme, settings and its coresponding containers will be themed when i redo BetterSettings addon, chat will be themed in BetterChat addon after it. Will this be enough to publish this theme or may i need to do those addons first?
